### ISSUE TITLE
feat: smart contract events

### ISSUE THREAD

**Issue by mfw78** [windingtree/videre-contracts#2]
**Problem**
Events are required for the `service provider` and `consumer` to trigger various actions.

**Events**

***Stays***

From a 'stays' perspective, require events for:

- [ ] making a `deal`. Should contain stub `id`, stub state `hash`, `serviceProvider` id, and `consumer` address, ie. `Deal(bytes32 stubId,bytes32 stubState,bytes32 which,address who)`.
- [ ] changing the state of any `stub` - `Mutate(bytes32 stubId,bytes32 stubState)`
- [ ] moving ownership of the `stub` - `ChangeOwner(bytes32 stubId,address src,address dst)`

**TODO:** Anything else here for event management?

***Service Provider Treasury***

**TODO:** What are the use cases here for the service provider?

***Protocol treasury***

**TODO:** Are there any reasons to trigger events for the protocol treasury?
